import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";
import { generateCertificatePdf } from '@/lib/pdf';
import { sendCertificateEmail } from '@/lib/email';

async function createCertificateIfMissing(submission: any, companyId: string) {
  // Avoid duplicate certificates for same submission/student
  const studentEmail = submission.student?.email || `${submission.teamName}@example.com`;
  const exists = await prisma.certificate.findFirst({
    where: {
      projectId: submission.projectId,
      studentEmail,
    },
  });
  if (exists) return exists;

  const issueDate = new Date().toISOString().split("T")[0];
  const expiryDate = new Date(new Date().setFullYear(new Date().getFullYear() + 2))
    .toISOString()
    .split("T")[0];

  const cert = await prisma.certificate.create({
    data: {
      certId: `CERT-${Math.floor(100000 + Math.random() * 900000)}`,
      title: `Accredited Certification in ${submission.project.title}`,
      studentName: submission.student?.name || submission.teamName,
      studentEmail,
      issueDate,
      expiryDate,
      status: "Verified",
      companyId,
      projectId: submission.projectId,
    },
  });

  // Attempt to generate PDF and email it to the student. Failures here should not break the main flow.
  try {
    const company = await prisma.user.findUnique({ where: { id: companyId } });
    const companyName = company?.name;

    const pdfBuffer = await generateCertificatePdf({
      certId: cert.certId,
      title: cert.title,
      studentName: cert.studentName,
      studentEmail: cert.studentEmail,
      issueDate: cert.issueDate,
      expiryDate: cert.expiryDate,
      companyName,
    });

    await sendCertificateEmail({
      to: cert.studentEmail,
      subject: `Your Certificate - ${cert.title}`,
      text: `Congratulations ${cert.studentName}! Attached is your certificate generated by CertiTask.`,
      attachment: { filename: `${cert.certId}.pdf`, content: pdfBuffer },
    });
  } catch (err) {
    console.error('Failed to generate or send certificate PDF:', err);
  }

  return cert;
}
export async function PATCH(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getSession();
  if (!session || (session.role !== "COMPANY" && session.role !== "STUDENT")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const { id } = await params;
    const payload = await req.json();
    const { status, feedback } = payload;

    if (!status) {
      return NextResponse.json({ error: "Status is required" }, { status: 400 });
    }

    // Load submission (company must own the project for company actions)
    const submission = await prisma.submission.findUnique({
      where: { id },
      include: { project: true, student: true },
    });

    if (!submission) {
      return NextResponse.json({ error: "Submission not found" }, { status: 404 });
    }

    // COMPANY actions
    if (session.role === "COMPANY") {
      if (submission.project.companyId !== session.userId) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
      }

      // Company confirms deliverable
      if (status === "CompanyApproved") {
        // If student already confirmed, issue certificate and set final status to Approved
        if (submission.status === "StudentConfirmed") {
          const cert = await createCertificateIfMissing(submission, session.userId);
          const updated = await prisma.submission.update({
            where: { id },
            data: { status: "Approved", feedback },
          });
          return NextResponse.json({ success: true, submission: updated, certificate: cert });
        } else {
          // Mark as company-approved and wait for student confirmation
          const updated = await prisma.submission.update({
            where: { id },
            data: { status: "CompanyApproved", feedback },
          });
          return NextResponse.json({ success: true, submission: updated });
        }
      }

      // Company rejects
      if (status === "Rejected") {
        const updated = await prisma.submission.update({
          where: { id },
          data: { status: "Rejected", feedback },
        });
        return NextResponse.json({ success: true, submission: updated });
      }

      // Other status updates by company
      const updated = await prisma.submission.update({
        where: { id },
        data: { status, ...(feedback && { feedback }) },
      });
      return NextResponse.json({ success: true, submission: updated });
    }

    // STUDENT actions
    if (session.role === "STUDENT") {
      // Only the submitting student/team may confirm
      if (submission.studentId && submission.studentId !== session.userId) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
      }

      if (status === "StudentConfirmed") {
        // If company already approved, issue certificate and set final status to Approved
        if (submission.status === "CompanyApproved") {
          const cert = await createCertificateIfMissing(submission, submission.project.companyId);
          const updated = await prisma.submission.update({
            where: { id },
            data: { status: "Approved" },
          });
          return NextResponse.json({ success: true, submission: updated, certificate: cert });
        } else {
          // Mark as student-confirmed and wait for company confirmation
          const updated = await prisma.submission.update({
            where: { id },
            data: { status: "StudentConfirmed" },
          });
          return NextResponse.json({ success: true, submission: updated });
        }
      }

      // Student cannot perform other status changes
      return NextResponse.json({ error: "Invalid action" }, { status: 400 });
    }

    return NextResponse.json({ error: "Unhandled role" }, { status: 400 });
  } catch (error) {
    console.error("Update submission status error:", error);
    return NextResponse.json({ error: "Failed to update submission status" }, { status: 500 });
  }
}
